//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBR.Evento.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorreoDifusion
    {
        public int IdCorreoDifusion { get; set; }
        public Nullable<int> IdCorreo { get; set; }
        public Nullable<int> IdEvento { get; set; }
        public int IdPersona { get; set; }
        public string Correo { get; set; }
        public int Estado { get; set; }
        public string ErrorMensaje { get; set; }
        public string ErrorStackTrace { get; set; }
        public int UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> NumeroEnvio { get; set; }
        public Nullable<bool> Pago { get; set; }
    
        public virtual Correo Correo1 { get; set; }
    }
}
