//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBR.Evento.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventoTema
    {
        public int IdEventoTema { get; set; }
        public Nullable<int> IdEvento { get; set; }
        public Nullable<int> TipoTema { get; set; }
    
        public virtual Evento Evento { get; set; }
    }
}
