//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBR.Evento.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evento()
        {
            this.EventoCorreo = new HashSet<EventoCorreo>();
            this.EventoTema = new HashSet<EventoTema>();
            this.EventoUsuario = new HashSet<EventoUsuario>();
            this.Inscripcion = new HashSet<Inscripcion>();
            this.Modulo = new HashSet<Modulo>();
            this.VirtualContenido = new HashSet<VirtualContenido>();
            this.VirtualVideo = new HashSet<VirtualVideo>();
        }
    
        public int IdEvento { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> Modalidad { get; set; }
        public string NombreEvento { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Expositor { get; set; }
        public string ImagenEvento { get; set; }
        public string DocumentoFotocheck { get; set; }
        public string DocumentoCertificado { get; set; }
        public string DocumentoCertificadoImprimir { get; set; }
        public string DocumentoCertificadoExpositor { get; set; }
        public Nullable<int> Horas { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<decimal> NotaAprobatoria { get; set; }
        public string Costo { get; set; }
        public Nullable<decimal> CostoValor { get; set; }
        public Nullable<decimal> CostoValorPromocional { get; set; }
        public Nullable<bool> DetallarCertificado { get; set; }
        public Nullable<bool> GenerarCertificado { get; set; }
        public bool Estado { get; set; }
        public Nullable<System.Guid> rowid { get; set; }
        public int UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventoCorreo> EventoCorreo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventoTema> EventoTema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventoUsuario> EventoUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscripcion> Inscripcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Modulo> Modulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VirtualContenido> VirtualContenido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VirtualVideo> VirtualVideo { get; set; }
    }
}
