//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBR.Evento.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventoUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventoUsuario()
        {
            this.EventoUsuarioVirtualVideo = new HashSet<EventoUsuarioVirtualVideo>();
        }
    
        public int IdEventoUsuario { get; set; }
        public Nullable<int> IdEvento { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<System.DateTime> FechaUltimoAcceso { get; set; }
        public Nullable<decimal> NotaFinal { get; set; }
        public Nullable<bool> Abierto { get; set; }
        public bool Estado { get; set; }
        public int UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventoUsuarioVirtualVideo> EventoUsuarioVirtualVideo { get; set; }
        public virtual Evento Evento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
