//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBR.Evento.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripcion
    {
        public int IdInscripcion { get; set; }
        public Nullable<int> IdEvento { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public Nullable<int> EstadoPago { get; set; }
        public Nullable<int> TipoPago { get; set; }
        public Nullable<bool> EntregaCertificado { get; set; }
        public Nullable<int> TipoModalidad { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string NombreBanco { get; set; }
        public Nullable<System.DateTime> FechaOperacion { get; set; }
        public string NumeroOperacion { get; set; }
        public Nullable<int> NumeroCertificado { get; set; }
        public string Certificado { get; set; }
        public Nullable<decimal> Nota { get; set; }
        public Nullable<int> TipoInscripcion { get; set; }
        public string Ruc { get; set; }
        public bool Estado { get; set; }
        public int UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> rowguid { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Evento Evento { get; set; }
    }
}
